// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjIYXpAuv1PLd2rzDfZUFN3203Nc1IrxM',
    appId: '1:385013935634:web:eacb7b592bac26d91eb2cb',
    messagingSenderId: '385013935634',
    projectId: 'home-scouter-50835',
    authDomain: 'home-scouter-50835.firebaseapp.com',
    storageBucket: 'home-scouter-50835.firebasestorage.app',
    measurementId: 'G-QXYEJ431K6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeg6_ns4EmFtkCB4hb66Si79zZ7ZlWkXk',
    appId: '1:385013935634:android:ae5a07cd3bc1f1c11eb2cb',
    messagingSenderId: '385013935634',
    projectId: 'home-scouter-50835',
    storageBucket: 'home-scouter-50835.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcc6l_A7hcjssPN9AVdXQo5mFJoqu1wLA',
    appId: '1:385013935634:ios:6515f46acceb410f1eb2cb',
    messagingSenderId: '385013935634',
    projectId: 'home-scouter-50835',
    storageBucket: 'home-scouter-50835.firebasestorage.app',
    iosBundleId: 'com.example.homescouterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcc6l_A7hcjssPN9AVdXQo5mFJoqu1wLA',
    appId: '1:385013935634:ios:6515f46acceb410f1eb2cb',
    messagingSenderId: '385013935634',
    projectId: 'home-scouter-50835',
    storageBucket: 'home-scouter-50835.firebasestorage.app',
    iosBundleId: 'com.example.homescouterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjIYXpAuv1PLd2rzDfZUFN3203Nc1IrxM',
    appId: '1:385013935634:web:b8dcc886814b26901eb2cb',
    messagingSenderId: '385013935634',
    projectId: 'home-scouter-50835',
    authDomain: 'home-scouter-50835.firebaseapp.com',
    storageBucket: 'home-scouter-50835.firebasestorage.app',
    measurementId: 'G-LKKB76HNLL',
  );
}
